### ISSUE TITLE
Request for Volunteers to Participate in Thesis Case Study on Machine Learning and Hieroglyphs

### ISSUE THREAD

**Issue by Iolanthe007** [googleartsculture/workbench#3]
**Thesis Title**: Innovations in Machine Learning: A Case Study of the Fabricius Workbench 
**Thesis Subtitle**: A Digital Tool for Translating Ancient Egyptian Hieroglyphs? 
  
Fabricius was initially commissioned by Ubisoft back in 2017 as a result of the process that produced their video game Assassin’s Creed: Origins, set in Ptolemaic Egypt. Psycle Interactive is the digital production company that has been developing the program since then. Ubisoft have since become much less involved and the project has subsequently been taken up by Google, specifically, Google Arts and Culture. Dr Brian Ballsun-Stanton and Dr Alex Woods have been consulting with Psycle and Google for the past few years, giving feedback on the program’s performance and usability. I have been involved with the project since the latter part of 2019, and am focusing on its potential benefits to epigraphic research practice for my Masters of Research thesis. To clarify, however, my focus is not necessarily on how the program itself can be integrated into epigraphic methods, but more on using the case study of Fabricius to demonstrate ways in which epigraphic methods can be modified or improved using technology.

**Case Study Details**: 
  
The case study will involve:
1. A pre-translation interview via Zoom (this is to establish the participant’s level of experience with hieroglyphs and ingoing attitude towards and experience with using technology in research); 
2. The first translation. This may either be manual or using Fabricius – there will be an A and a B group and they will be doing the opposite order to each other. 
3. The second translation. This will involve the opposite method to that used in the first translation, whichever that might be. There are two different texts that will be used. Both translations will be conducted via Zoom. The participant will be required to share screens with me when using the computer for anything (whether use of Fabricius or typing up transliterations) and will be asked to talk through their thought processes out loud.
4. A post-translation interview via Zoom (this is to collect feedback on how well the program operated, its usability, observed benefits, frustrations, potential improvements, etc.). 
  
Each Zoom session will ideally take place within 1-2 days of each other (preferably within 1 day) and the sessions will vary in length, with the translation sessions being the longest. 

If you are interested in participating in a case study that puts the Google Arts and Culture hieroglyphic translating program Fabricius to the test, please contact bree.kelly@hdr.mq.edu.au. Engage with innovative new technology and discover how research can be re-imagined with the help of computers and machine learning.

**Comment by Denubis** [comment]
Well, not so much approved as suggested by me :) Bree, maybe edit that last line out?  
@justingrayston it'd be great if any of your folks could participate.

**Comment by Denubis** [comment]
@justingrayston The masters project has just been submitted for review. Can we close this issue? (We'll open a new issue when her thesis passes so there's a good link to it from here)
